trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '558656f3-af39-446e-9c92-9a73618f54b0'
  imageRepository: 'akashnodejsdockerimage'
  containerRegistry: 'mynodeappacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/routes/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent pool name (since you are using a self-hosted macOS agent)
  poolName: 'Default'  # Refer to your self-hosted pool name

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default # Use your self-hosted agent pool name (Default)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)